name: RELEASE DEPLOY

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: 1. Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 2. Build demo
      run: |
        yarn install
        yarn build
        ls

  release:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password and login
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEMO_HOST }}
          username: ${{ secrets.DEMO_USERNAME }}
          password: ${{ secrets.DEMO_PASSWORD }}
          port: ${{ secrets.DEMO_PORT }}
          target: demo/dist
          rm: true
